// app/src/pages/contact-us.vue
<template>
  <div>
    <q-img src="@/assets/images/tucan.jpg" height="500">
      <h1>About Us</h1></q-img
    >
    <h2>Contact Details</h2>
    <div class="container">
      <div class="container">
        <p>icon</p>

        <div class="vcontainer">
          <h2>Call Us</h2>
          <p>+33970406998</p>
        </div>
      </div>
      <div class="container">
        <p>icon</p>

        <div class="vcontainer">
          <h2>Email Us</h2>
          <p>contact@harmonia-eko.ooo</p>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.container {
  display: flex;
  flex-direction: row;
  font-size: large;
  width: 50%;
  font-size: 1.7em;
}
.vcontainer {
  display: flex;
  flex-direction: column;
  font-size: large;
  width: 50%;
  font-size: 1em;
}
h1 {
  color: white;
  font-size: 10em;
}
q-img {
  align-items: bottom;
  display: flex;
}
h2 {
  text-align: center;
}
</style>

// v8/pages/ContactUs.tsx
import React from 'react'
import Navbar from '../components/Navbar'
export default function ContactUs() {
    return (
        <div className="w-100" style={{height:'100vh',backgroundImage:'url(/assets/images/tucan.jpg)',backgroundSize:'auto 100%'}}>
            <Navbar/>
            <h1>Contact Details</h1>
            <div >
                <div>
                    <p>icon</p>
                    <div>
                        <h2>Call Us</h2>
                        <p>+33970406998</p>
                    </div>
                </div>
                    <div >
                        <p>icon</p>
                        <div >
                            <h2>Email Us</h2>
                            <p>contact@harmonia-eko.ooo</p>
                        </div>
                    </div>
                </div>
        </div>
    )
}
